-- Perki catalogue expansion — PROPOSED, do not run until Ollie approves.
-- Verified against official UK provider pages 2026-07-08. Mirror into Perks_Rows.xlsx after running.
-- Conventions: perk_id = provider-tier-title slug; perks assigned to the LOWEST tier that includes them
-- (hierarchical providers); variant providers get one row per variant.

begin;

-- ═══ AMERICAN EXPRESS ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('american-express-rewards-purchase-protection','American Express','American Express','Rewards','feature','Purchase protection','Purchase protection','Cover for theft or accidental damage to eligible items bought on the card within 90 days of purchase, at no extra cost.','Protection','NONE',0.0,'Usage: Ongoing.','https://www.americanexpress.com/uk/customer-service/faq.how-does-american-express-refund-protection-work.html','2026-07-08'),
('american-express-rewards-refund-protection','American Express','American Express','Rewards','feature','Refund protection','Refund protection','Refund of up to £200 per item if a retailer will not take back an unused eligible item within 90 days of purchase.','Protection','ANNUALLY',0.0,'Usage: Up to £750 per 12 months.','https://www.americanexpress.com/uk/customer-service/faq.how-does-american-express-refund-protection-work.html','2026-07-08'),
('american-express-gold-120-deliveroo-credit','American Express','American Express','Gold','perk','£120 Deliveroo credit','£120 Deliveroo credit','Get £5 back twice a month on Deliveroo orders of £5 or more, up to £120 a year. Enrolment required.','Food','MONTHLY',16.25,'Usage: 2 x £5 credits/month.','https://www.americanexpress.com/en-gb/benefits/explore-your-gold-card/get-started/','2026-07-08'),
('american-express-gold-travel-inconvenience-cover','American Express','American Express','Gold','feature','Travel inconvenience cover','Travel inconvenience cover','Insurance for travel mishaps such as flight delay and lost baggage when you pay with the card.','Insurance','NONE',16.25,'Usage: Ongoing.','https://www.americanexpress.com/en-gb/benefits/explore-your-gold-card/get-started/','2026-07-08'),
('american-express-gold-hotel-collection-benefits','American Express','American Express','Gold','perk','The Hotel Collection benefits','The Hotel Collection benefits','US$100 hotel credit and elevated benefits at over 500 upscale hotels on stays of two or more nights booked through Amex Travel.','Travel','NONE',16.25,'Usage: 1 credit/room per stay.','https://www.americanexpress.com/en-gb/benefits/explore-your-gold-card/travel/','2026-07-08'),
('american-express-platinum-400-global-dining-credit','American Express','American Express','Platinum','perk','£400 Global Dining Credit','£400 Global Dining Credit','Up to £200 at participating UK restaurants and £200 abroad each year at over 2,000 handpicked venues. Enrolment required.','Food','ANNUALLY',54.17,'Usage: £100 UK and £100 abroad per half year, resets 1 January and 1 July.','https://www.americanexpress.com/en-gb/benefits/dining/the-platinum-card/','2026-07-08'),
('american-express-platinum-fine-hotels-resorts','American Express','American Express','Platinum','perk','Fine Hotels + Resorts benefits','Fine Hotels + Resorts benefits','Guaranteed 4pm late check-out, noon check-in and room upgrade when available, daily breakfast for two and an experience credit at 1,300 properties.','Travel','NONE',54.17,'Usage: Per stay, booked via Amex Travel.','https://www.americanexpress.com/en-gb/benefits/travel/hotels/the-platinum-card/fine-hotels-and-resorts/','2026-07-08'),
('american-express-platinum-car-hire-insurance','American Express','American Express','Platinum','feature','Car hire insurance','Car hire insurance','Car rental cover included with Platinum travel insurance, on top of what car hire firms offer.','Insurance','NONE',54.17,'Usage: Ongoing, terms and exclusions apply.','https://www.americanexpress.com/en-gb/benefits/insurance-and-protection/the-platinum-card/','2026-07-08');

-- ═══ SANTANDER EDGE ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('santander-everyday-santander-boosts-rewards','Santander','Santander Edge','Everyday','perk','Santander Boosts rewards','Santander Boosts rewards','Cashback offers, vouchers and prize draws tailored to you when you activate offers and pay with your Santander card.','Rewards','NONE',0.0,'Usage: Ongoing, activate offers first.','https://www.santander.co.uk/personal/support/understanding-our-services/boosts','2026-07-08'),
('santander-edge-fee-free-debit-card-abroad','Santander','Santander Edge','Edge','feature','Fee-free debit card use abroad','Fee-free debit card use abroad','0% foreign conversion fee on debit card purchases and cash withdrawals in local currency outside the UK.','Currency','NONE',3.0,'Usage: Ongoing, from 3 working days after opening.','https://www.santander.co.uk/personal/current-accounts/edge-current-account','2026-07-08'),
('santander-edge-fee-free-international-payments','Santander','Santander Edge','Edge','feature','Fee-free international payments','Fee-free international payments','CHAPS, international and foreign currency payments are free from this account, waiving the usual £25 fee.','Transfers','NONE',3.0,'Usage: Ongoing.','https://www.santander.co.uk/personal/current-accounts/edge-current-account','2026-07-08');

-- ═══ NATIONWIDE ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('nationwide-flexaccount-50-interest-free-overdraft','Nationwide','Nationwide FlexPlus','FlexAccount','feature','£50 interest-free overdraft','£50 interest-free overdraft','The first £50 of an arranged overdraft is interest-free, subject to eligibility.','Banking','NONE',0.0,'Usage: Ongoing.','https://www.nationwide.co.uk/current-accounts/flexaccount','2026-07-08'),
('nationwide-flexaccount-member-only-savings','Nationwide','Nationwide FlexPlus','FlexAccount','feature','Member-only savings access','Member-only savings access','Current account members can open exclusive savings accounts such as Flex Regular Saver, plus member-only credit cards and loans.','Savings','NONE',0.0,'Usage: Ongoing.','https://www.nationwide.co.uk/current-accounts/flexaccount','2026-07-08'),
('nationwide-flexaccount-175-switching-bonus','Nationwide','Nationwide FlexPlus','FlexAccount','perk','£175 switching bonus','£175 switching bonus','Get £175 for a full switch to Nationwide using the Current Account Switch Service. Limited time, conditions apply.','Banking','NONE',0.0,'Usage: One-time, first switch only. Re-verify periodically, offer is time-limited.','https://www.nationwide.co.uk/current-accounts/flexaccount','2026-07-08'),
('nationwide-flexplus-fee-free-card-abroad','Nationwide','Nationwide FlexPlus','FlexPlus','feature','Fee-free card use abroad','Fee-free card use abroad','No Nationwide charges for using your debit card abroad or in a non-sterling currency.','Currency','NONE',18.0,'Usage: Ongoing.','https://www.nationwide.co.uk/current-accounts/flexplus','2026-07-08');

-- ═══ BRITISH AIRWAYS CLUB ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('british-airways-blue-household-account','British Airways','The British Airways Club','Blue','feature','Household account','Household account','Pool Avios with family and friends at your address through a shared household account.','Rewards','NONE',0.0,'Usage: All household account members must be registered at the same address.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-bronze-priority-boarding','British Airways','The British Airways Club','Bronze','perk','Priority boarding','Priority boarding','Board ahead of general boarding on British Airways flights from Bronze tier upwards.','Travel','NONE',0.0,'Usage: Excludes London City Airport at Bronze.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-bronze-wine-flyer-discount','British Airways','The British Airways Club','Bronze','discount','The Wine Flyer discount','The Wine Flyer discount','5% off almost all purchases at The Wine Flyer, rising to 10% at Silver and 15% at Gold.','Shopping','NONE',0.0,'Usage: Ongoing, some exclusions apply.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-silver-extra-baggage-allowance','British Airways','The British Airways Club','Silver','perk','Extra baggage allowance','Extra baggage allowance','Check in additional baggage on top of your ticket allowance as a Silver or Gold member.','Travel','NONE',0.0,'Usage: Does not apply on hand baggage only fares.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-silver-reservation-assurance','British Airways','The British Airways Club','Silver','feature','Reservation Assurance','Reservation Assurance','Guaranteed a seat on your chosen British Airways flight even if it is fully booked, on eligible fares.','Travel','NONE',0.0,'Usage: Silver and Gold members on qualifying bookings.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-gold-upgrade-vouchers','British Airways','The British Airways Club','Gold','perk','Gold upgrade vouchers','Gold upgrade vouchers','Earn a Gold upgrade for two voucher at 35,000 tier points in a year, and two upgrade for one vouchers at 50,000.','Rewards','ANNUALLY',0.0,'Usage: Thresholds measured within one membership year.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-gold-concorde-room-access','British Airways','The British Airways Club','Gold','perk','Concorde Room access','Concorde Room access','Access BA''s exclusive Concorde Room lounges at 65,000 tier points in a year, then 40,000 in following years.','Travel','ANNUALLY',0.0,'Usage: Minimum tier points from BA marketed flights, add-ons or BA Holidays.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08'),
('british-airways-gold-partner-status-cards','British Airways','The British Airways Club','Gold','perk','Partner and member status cards','Partner and member status cards','Gold Guest List: one Gold partner card and two Silver member cards for family or friends at 65,000 tier points, then 40,000 thereafter.','Rewards','ANNUALLY',0.0,'Usage: Minimum tier points from BA marketed flights, add-ons or BA Holidays.','https://www.britishairways.com/content/the-british-airways-club/about-the-club/tiers-and-benefits/compare-the-tiers','2026-07-08');

-- ═══ RAILCARD (variant-specific) ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('railcard-family-friends-60-off-kids-fares','Railcard','Railcard','Family & Friends','discount','60% off kids'' fares','60% off kids'' fares','Up to four kids aged 5 to 15 travel with 60% off child fares, alongside a third off for up to four adults on one card.','Family','NONE',2.92,'Usage: A cardholder and at least one child on a child rate ticket must travel.','https://www.railcard.co.uk/family-and-friends/','2026-07-08'),
('railcard-two-together-first-class-fares','Railcard','Railcard','Two Together','discount','First class fares included','First class fares included','A third off First Class as well as Standard Anytime, Off-Peak and Advance fares for the two named cardholders.','Travel','NONE',2.92,'Usage: Both named people must travel together; after 09:30 Mon-Fri, anytime weekends.','https://www.railcard.co.uk/two-together/','2026-07-08'),
('railcard-network-group-savings','Railcard','Railcard','Network','discount','Group savings on one card','Group savings on one card','Up to three additional adults get a third off and up to four kids get 60% off when travelling with the cardholder.','Travel','NONE',2.92,'Usage: Network Railcard area only; minimum fares and 10:00 Mon-Fri restriction apply.','https://www.railcard.co.uk/network/','2026-07-08'),
('railcard-disabled-persons-companion-third-off','Railcard','Railcard','Disabled Persons','discount','Companion travels for 1/3 off','Companion travels for 1/3 off','One adult companion travelling with you also gets a third off their fare.','Travel','NONE',2.0,'Usage: The companion must travel with you for the whole journey.','https://www.disabledpersons-railcard.co.uk/','2026-07-08'),
('railcard-disabled-persons-oyster-payg-discount','Railcard','Railcard','Disabled Persons','perk','Oyster pay as you go discount','Oyster pay as you go discount','Load your Railcard onto a registered Oyster card for a third off single pay as you go fares on London Underground and DLR.','Travel','NONE',2.0,'Usage: Ask staff at a London Underground station to set the discount.','https://www.disabledpersons-railcard.co.uk/','2026-07-08');
-- Partner offers: one row per variant
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified)
select 'railcard-' || lower(replace(replace(t.tier,' & ','-'),' ','-')) || '-partner-offers','Railcard','Railcard',t.tier,'perk','Partner offers and rewards','Partner offers and rewards','Exclusive deals from Railcard partners, such as Gousto, Craft Gin Club and Readly, alongside your travel savings.','Shopping','NONE',t.price,'Usage: Offers change regularly; see your Railcard''s offers section.','https://www.railcard.co.uk/','2026-07-08'
from (values ('16-25',2.92),('26-30',2.92),('Senior',2.92),('Two Together',2.92),('Family & Friends',2.92),('Network',2.92),('Disabled Persons',2.0)) as t(tier,price);
-- OPTIONAL (eligibility rule, not a benefit) — uncomment to include:
-- insert into perks (...) values ('railcard-16-25-mature-student-route', ... );

-- ═══ NATIONAL TRUST ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified)
select 'national-trust-' || lower(t.tier) || '-' || r.slug,'National Trust','National Trust Membership',t.tier,r.feature,r.title,r.title,r.description,r.category,r.reset_period,t.price,r.usage_notes,r.source_url,'2026-07-08'
from (values ('Individual',6.0),('Joint',11.6),('Family',14.7),('Life',202.5)) as t(tier,price)
cross join (values
 ('free-entry-to-trusts-overseas','perk','Free entry to trusts overseas','Free visiting arrangements with INTO partner heritage organisations abroad, from the National Trust for Scotland to the Bahamas National Trust.','Travel','NONE','Usage: Show a valid membership card; some sites offer discounted rather than free entry.','https://www.nationaltrust.org.uk/membership/international-national-trusts-organisation'),
 ('vote-at-the-agm','feature','Vote at the AGM','Vote on resolutions at the Annual General Meeting and help shape the direction of the National Trust.','Lifestyle','ANNUALLY','Usage: Details arrive in the digital AGM booklet each autumn.','https://www.nationaltrust.org.uk/membership/what-to-enjoy-as-a-member'),
 ('member-exclusive-competitions','competition','Member-exclusive competitions','Exclusive competitions, partner discounts and promotions through member emails.','Competition','NONE','Usage: Opt in to member emails through My Account.','https://www.nationaltrust.org.uk/membership/what-to-enjoy-as-a-member'),
 ('online-members-area','feature','Online members'' area','Access the online members'' area, home to content made exclusively for members.','Entertainment','NONE','Usage: Sign in through My Account.','https://www.nationaltrust.org.uk/membership/what-to-enjoy-as-a-member')
) as r(slug,feature,title,description,category,reset_period,usage_notes,source_url);
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified)
select 'national-trust-' || lower(t.tier) || '-new-member-guest-pass','National Trust','National Trust Membership',t.tier,'perk','New member guest pass','New member guest pass','Bring a friend or family member for free with a single-use guest pass when you join by annual Direct Debit online.','Family','NONE',t.price,'Usage: Single use, participating places only, excludes bank holiday weekends.','https://www.nationaltrust.org.uk/membership/enquiries/new-member-guest-pass-terms-and-conditions','2026-07-08'
from (values ('Individual',6.0),('Joint',11.6),('Family',14.7)) as t(tier,price);

-- ═══ TESCO ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('tesco-clubcard-points-on-fuel','Tesco','Tesco Clubcard','Clubcard','perk','Clubcard points on fuel','Clubcard points on fuel','Collect 1 point per 2 litres at Tesco petrol stations, or 1 point per £3 at Esso sites with a Tesco Express.','Automotive','NONE',0.0,'Usage: Scan your Clubcard or app when paying for fuel.','https://www.tesco.com/help/pages/clubcard-faqs/points/number-of-clubcard-points-you-can-collect-on-fuel','2026-07-08'),
('tesco-clubcard-clubcard-challenges','Tesco','Tesco Clubcard','Clubcard','competition','Clubcard Challenges','Clubcard Challenges','Personalised challenges in the Tesco app that award bonus points or coupons when completed, during promotional periods.','Rewards','NONE',0.0,'Usage: Opt in via the Clubcard tab in the Tesco app; rewards land within 72 hours.','https://www.tesco.com/help/pages/clubcard-faqs/points/how-to-collect-clubcard-points','2026-07-08');

-- ═══ BOOTS ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('boots-advantage-card-over-60s-rewards','Boots','Boots Advantage Card','Advantage Card','perk','Over 60s Rewards','Over 60s Rewards','Free club for members aged 60 or over giving 8 points per £1 on Boots own brands and selected exclusives.','Rewards','NONE',0.0,'Usage: Join free; excludes prescriptions, gift cards and some services.','https://www.boots.com/shopping/over60s','2026-07-08');
-- CONFLICT — resolve before running (see proposed-perk-additions.md #1):
-- ('boots-advantage-card-price-advantage-member-prices-v2', ... 'Price Advantage member prices' ...)

-- ═══ IKEA ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('ikea-ikea-family-member-food-offers','IKEA','IKEA Family','IKEA Family','discount','Member food offers','Member food offers','Member prices on a range of meals and drinks in the Swedish Restaurant and Swedish Food Market.','Food','NONE',0.0,'Usage: Scan your IKEA Family card when paying.','https://www.ikea.com/gb/en/ikea-family/benefits/','2026-07-08'),
('ikea-ikea-family-delivery-collection-savings','IKEA','IKEA Family','IKEA Family','perk','Delivery and collection savings','Delivery and collection savings','Member savings on delivery and Click and collect orders.','Shopping','NONE',0.0,'Usage: Log in to your IKEA Family account before ordering.','https://www.ikea.com/gb/en/ikea-family/benefits/','2026-07-08'),
('ikea-ikea-family-15-extra-buyback-resell','IKEA','IKEA Family','IKEA Family','perk','15% extra on Buyback & Resell','15% extra on Buyback & Resell','IKEA boosts the buyback value of your returned IKEA furniture by 15% for Family members.','Savings','NONE',0.0,'Usage: Bring eligible used IKEA furniture to a store''s Buyback & Resell service.','https://www.ikea.com/gb/en/ikea-family/benefits/','2026-07-08'),
('ikea-ikea-family-digital-receipts','IKEA','IKEA Family','IKEA Family','feature','Digital receipts','Digital receipts','Receipts are automatically saved to your account whenever you scan your digital IKEA Family card.','Shopping','NONE',0.0,'Usage: View receipts and purchase history in your membership space.','https://www.ikea.com/gb/en/ikea-family/benefits/','2026-07-08'),
('ikea-ikea-family-gift-registry','IKEA','IKEA Family','IKEA Family','feature','Gift registry','Gift registry','Create a gift registry for weddings and milestones, then share it with family and friends.','Lifestyle','NONE',0.0,'Usage: Build your registry in your IKEA Family account.','https://www.ikea.com/gb/en/ikea-family/benefits/','2026-07-08');

-- ═══ COSTCO ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('costco-gold-star-double-guarantee','Costco','Costco Membership','Gold Star','feature','Double Guarantee','Double Guarantee','Risk-free 100% satisfaction guarantee: Costco will refund your membership if unhappy, and refund most merchandise on return.','Protection','NONE',3.5,'Usage: Cancel at the membership desk for a fee refund.','https://www.costco.co.uk/membership','2026-07-08'),
('costco-gold-star-hearing-centre-services','Costco','Costco Membership','Gold Star','perk','Hearing centre services','Hearing centre services','Access to hearing centres in selected warehouses for hearing services and hearing aids at member value.','Wellness','NONE',3.5,'Usage: Available at warehouses with a hearing centre.','https://www.costco.co.uk/member-services','2026-07-08'),
('costco-gold-star-cake-deli-ordering','Costco','Costco Membership','Gold Star','perk','Cake and deli ordering','Cake and deli ordering','Pre-order celebration cakes and deli platters from the warehouse bakery and deli.','Food','NONE',3.5,'Usage: Order ahead and collect in warehouse.','https://www.costco.co.uk/member-services','2026-07-08'),
('costco-gold-star-ev-charging','Costco','Costco Membership','Gold Star','feature','EV charging at warehouses','EV charging at warehouses','Electric vehicle charging available at selected Costco warehouse locations.','Automotive','NONE',3.5,'Usage: Selected sites only.','https://www.costco.co.uk/member-services','2026-07-08'),
('costco-executive-only-coupons-events','Costco','Costco Membership','Executive','perk','Executive-only coupons and events','Executive-only coupons and events','Extra member-only coupons and special savings events through the year, exclusive to Executive members.','Savings','NONE',7.0,'Usage: Offers run periodically.','https://www.costco.co.uk/membership-executive-questions','2026-07-08');

-- ═══ ASOS ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('asos-premier-free-nominated-day-delivery','ASOS','ASOS Premier','Premier','perk','Free nominated day delivery','Free nominated day delivery','Pick the delivery day that suits you, free on orders of £15 or more.','Shopping','NONE',0.83,'Usage: Not available for the Channel Islands and some postcodes.','https://www.asos.com/customer-care/delivery/can-you-tell-me-more-about-your-asos-premier-service/','2026-07-08'),
('asos-premier-asos-world-auto-enrolment','ASOS','ASOS Premier','Premier','perk','ASOS.WORLD auto-enrolment','ASOS.WORLD auto-enrolment','Premier subscribers are automatically enrolled in ASOS.WORLD, the exclusive benefits and loyalty programme.','Rewards','NONE',0.83,'Usage: Automatic when you join Premier.','https://www.asos.com/discover/asos-world/','2026-07-08');

-- ═══ BLUE LIGHT CARD ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('blue-light-card-mobile-app-virtual-card','Blue Light Card','Blue Light Card','Blue Light Card','feature','Mobile app with virtual card','Mobile app with virtual card','Search brands and redeem discounts on the go with the Blue Light Card app and your virtual card.','Shopping','NONE',0.21,'Usage: Download the app and log in with your membership.','https://www.bluelightcard.co.uk/en/bluelightcardmobileapp','2026-07-08'),
('blue-light-card-member-competitions','Blue Light Card','Blue Light Card','Blue Light Card','competition','Member competitions and free tickets','Member competitions and free tickets','Regular member-only competitions, promotions and ballots for free tickets and exclusive experiences.','Competition','NONE',0.21,'Usage: Enter via the promotions section while logged in.','https://www.bluelightcard.co.uk/en/blccompetitions','2026-07-08'),
('blue-light-card-local-offers','Blue Light Card','Blue Light Card','Blue Light Card','perk','Local offers near you','Local offers near you','Browse and redeem discounts from local businesses in your area, alongside national brands.','Shopping','NONE',0.21,'Usage: Use the explore local offers tool on the website or app.','https://www.bluelightcard.co.uk/en/local-offers','2026-07-08');

-- ═══ AMAZON ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('amazon-prime-free-same-day-delivery','Amazon','Amazon Prime','Prime','feature','Free same-day delivery','Free same-day delivery','Free same-day and overnight delivery to eligible postcodes on orders over £20.','Shopping','NONE',8.99,'Usage: £1.99 per delivery on eligible orders under £20.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-amazon-fresh-grocery','Amazon','Amazon Prime','Prime','feature','Amazon Fresh grocery delivery','Amazon Fresh grocery delivery','Same-day and next-day delivery of fresh and frozen groceries, free on orders over £60.','Food','NONE',8.99,'Usage: Minimum order £15; selected regions only.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-morrisons-groceries','Amazon','Amazon Prime','Prime','feature','Morrisons groceries on Amazon','Morrisons groceries on Amazon','Same-day and next-day Morrisons grocery delivery, free on orders over £60.','Food','NONE',8.99,'Usage: Minimum order £15; selected regions only.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-first-reads','Amazon','Amazon Prime','Prime','perk','First Reads early book access','First Reads early book access','Download a new Kindle book every month from the First Reads picks at no extra cost.','Entertainment','MONTHLY',8.99,'Usage: Choose from that month''s First Reads selection.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-music-unlimited-discount','Amazon','Amazon Prime','Prime','discount','Music Unlimited member discount','Music Unlimited member discount','Discounted Amazon Music Unlimited monthly plan, plus annual plans exclusive to Prime members.','Streaming','NONE',8.99,'Usage: UK resident Prime members only.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-luna-games','Amazon','Amazon Prime','Prime','feature','Amazon Luna games included','Amazon Luna games included','Play a selection of Amazon Luna cloud games at no additional cost.','Entertainment','NONE',8.99,'Usage: Access via Amazon Luna.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-family-benefit-sharing','Amazon','Amazon Prime','Prime','feature','Amazon Family benefit sharing','Amazon Family benefit sharing','Share Prime benefits with one other adult and up to four children in your household.','Family','NONE',8.99,'Usage: Not available on student or 18-24 memberships.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G6LDPN7YJHYKH2J6','2026-07-08'),
('amazon-prime-student-six-month-trial','Amazon','Amazon Prime','Prime Student','perk','Six-month free Prime trial','Six-month free Prime trial','Six months of Prime free before the 50% discounted membership begins.','Shopping','NONE',4.49,'Usage: Renews automatically after the trial.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=GAHEWLGGJTWD9NK5','2026-07-08'),
('amazon-prime-student-textbook-discount','Amazon','Amazon Prime','Prime Student','discount','10% off thousands of textbooks','10% off thousands of textbooks','Student-exclusive discount on thousands of textbooks.','Education','NONE',4.49,'Usage: Part of the exclusive student offers programme.','https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=GAHEWLGGJTWD9NK5','2026-07-08');
-- OPTIONAL (UK rollout timing unclear) — uncomment to include:
-- ('amazon-prime-alexa-plus', ... 'Alexa+ included with Prime' ...)

-- ═══ SPOTIFY ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('spotify-individual-15-hours-audiobooks','Spotify','Spotify Premium','Individual','feature','15 hours of audiobooks a month','15 hours of audiobooks a month','Listen to 15 hours a month from the audiobooks subscriber catalogue of over 700,000 titles.','Entertainment','MONTHLY',12.99,'Usage: Unused hours expire at month end.','https://www.spotify.com/uk/premium/','2026-07-08'),
('spotify-individual-lossless-audio','Spotify','Spotify Premium','Individual','feature','Lossless audio quality','Lossless audio quality','Stream music in lossless audio quality.','Streaming','NONE',12.99,'Usage: Included on all Premium plans.','https://www.spotify.com/uk/premium/','2026-07-08'),
('spotify-individual-jam-listening','Spotify','Spotify Premium','Individual','feature','Listen with friends in real time','Listen with friends in real time','Start a Jam and listen together with friends in real time.','Entertainment','NONE',12.99,'Usage: Included on all Premium plans.','https://www.spotify.com/uk/premium/','2026-07-08'),
('spotify-individual-ai-dj','Spotify','Spotify Premium','Individual','feature','AI DJ personalised sessions','AI DJ personalised sessions','DJ plays favourites you love and introduces new genres, playlists and artists based on your taste.','Streaming','NONE',12.99,'Usage: Find DJ via search or the home screen.','https://support.spotify.com/uk/article/dj/','2026-07-08'),
('spotify-duo-audiobooks-plan-manager','Spotify','Spotify Premium','Duo','feature','Audiobooks for the plan manager','Audiobooks for the plan manager','15 hours a month of audiobook listening for the plan manager.','Entertainment','MONTHLY',17.99,'Usage: Plan manager only; other members can buy an add-on.','https://www.spotify.com/uk/duo/','2026-07-08'),
('spotify-family-audiobooks-plan-manager','Spotify','Spotify Premium','Family','feature','Audiobooks for the plan manager','Audiobooks for the plan manager','15 hours a month of audiobook listening for the plan manager.','Entertainment','MONTHLY',21.99,'Usage: Plan manager only; members can buy an add-on.','https://www.spotify.com/uk/family/','2026-07-08'),
('spotify-family-managed-under-13-accounts','Spotify','Spotify Premium','Family','feature','Managed accounts for under-13s','Managed accounts for under-13s','Create music-only accounts for listeners under 13 where you decide what they can play.','Family','NONE',21.99,'Usage: Remove artists or songs, block videos and explicit content.','https://www.spotify.com/uk/family/','2026-07-08');

-- ═══ PRET / NANDO'S / VODAFONE ═══
insert into perks (perk_id, provider, membership, tier, feature, titlegroup, title, description, category, reset_period, price, usage_notes, source_url, last_verified) values
('pret-free-pret-perks-rewards','Pret','Club Pret','Free','perk','Pret Perks rewards scheme','Pret Perks rewards scheme','Collect stars on purchases and earn rewards through the Pret app.','Rewards','NONE',0.0,'Usage: Join free via the Pret app.','https://www.pret.co.uk/en-GB/pret-perks-rewards','2026-07-08'),
('nandos-rewards-bonus-chilli-sign-up','Nando''s','Nando''s Rewards','Nando''s Rewards','perk','Bonus chilli on sign-up','Bonus chilli on sign-up','Get a bonus chilli just for registering your Nando''s account.','Rewards','NONE',0.0,'Usage: One bonus chilli on registration; chillies expire after one year.','https://www.nandos.co.uk/rewards','2026-07-08'),
('vodafone-veryme-25-off-local-coffee','Vodafone','VeryMe Rewards','VeryMe','discount','25% off local coffee shops','25% off local coffee shops','25% off barista-made drinks at independent coffee shops with a free 12-month Local Blend membership.','Food','NONE',0.0,'Usage: Activate through VeryMe Rewards in the My Vodafone app.','https://www.vodafone.co.uk/my-vodafone-account/my-vodafone-app/vodafone-veryme-rewards','2026-07-08'),
('vodafone-veryme-2-for-1-eat-local','Vodafone','VeryMe Rewards','VeryMe','discount','2-for-1 meals with Eat Local','2-for-1 meals with Eat Local','2-for-1 meals and 25% off food and drink at independent restaurants with a free 12-month Eat Local membership.','Food','NONE',0.0,'Usage: Activate through VeryMe Rewards in the My Vodafone app.','https://www.vodafone.co.uk/my-vodafone-account/my-vodafone-app/vodafone-veryme-rewards','2026-07-08'),
('vodafone-veryme-56-off-days-out','Vodafone','VeryMe Rewards','VeryMe','discount','Up to 56% off days out','Up to 56% off days out','VeryMe Days Out, powered by Kids Pass, gives up to 56% off hundreds of UK attractions.','Family','NONE',0.0,'Usage: Covers aquariums, museums, theme parks and cinemas.','https://www.vodafone.co.uk/my-vodafone-account/my-vodafone-app/vodafone-veryme-rewards','2026-07-08'),
('vodafone-veryme-caffe-nero-offers','Vodafone','VeryMe Rewards','VeryMe','perk','Caffè Nero coffee offers','Caffè Nero coffee offers','Rotating Caffè Nero perks, from free coffee giveaways to any barista-made drink for £1.','Food','NONE',0.0,'Usage: Check the day''s offer in VeryMe Rewards.','https://www.vodafone.co.uk/my-vodafone-account/my-vodafone-app/vodafone-veryme-rewards','2026-07-08'),
('vodafone-veryme-together-monthly-extras','Vodafone','VeryMe Rewards','VeryMe','perk','Vodafone Together monthly extras','Vodafone Together monthly extras','Vodafone Together customers unlock exclusive VeryMe Rewards every month for the whole family.','Rewards','MONTHLY',0.0,'Usage: Requires combined broadband and mobile.','https://www.vodafone.co.uk/my-vodafone-account/my-vodafone-app/vodafone-veryme-rewards','2026-07-08');

-- ═══════════════ CORRECTIONS (FIX items) ═══════════════

-- Santander: overseas spending belongs at Edge (Edge Up inherits)
update perks set tier='Edge', price=3.0 where provider='Santander' and tier='Edge Up' and title='Fee-free overseas spending';
update perks set description='1% cashback on council tax, energy, water and communications Direct Debits, capped at £10 a month on Edge and £15 on Edge Up. Requires monthly pay-in and two Direct Debits.' where provider='Santander' and title='Cashback on household bills';

-- Nationwide: Fairer Share conditionality
update perks set description='Nationwide has paid an annual Fairer Share payment for four years running (£100 in June 2026). Requires a qualifying current account plus savings or a mortgage; paid at Nationwide''s discretion and not guaranteed.' where perk_id='nationwide-flexaccount-fairer-share-payment';

-- British Airways: retier and rename
delete from perks where provider='British Airways' and tier='Gold' and title='Priority boarding and baggage';
update perks set title='Priority baggage handling', titlegroup='Priority baggage handling', description='Your checked baggage is tagged priority and unloaded first as a Silver or Gold member.' where provider='British Airways' and tier='Silver' and title='Priority boarding and baggage';
update perks set title='Member-only offers', titlegroup='Member-only offers', description='Member-only offers including Avios seat sale promotions.' where provider='British Airways' and tier='Blue' and title='Avios seat sales';

-- Railcard: prices and conditions
update perks set price=2.5 where provider='Railcard' and tier in ('Two Together','Family & Friends','Network');
update perks set price=1.67 where provider='Railcard' and tier='Disabled Persons';
update perks set usage_notes='Usage: Both named cardholders must travel together; after 09:30 Mon-Fri, anytime weekends and public holidays.' where provider='Railcard' and tier='Two Together' and title='One third off rail fares';
update perks set usage_notes='Usage: London and South East area only; minimum fare applies Monday to Friday.' where provider='Railcard' and tier='Network' and title='One third off rail fares';

-- National Trust: parking wording
update perks set description='Free parking at many National Trust coast and countryside car parks.' where provider='National Trust' and title='Free parking';

-- Tesco: Clubcard Plus caveats
update perks set usage_notes='Usage: In-store only; discount capped at £20 per shop and £40 in any month.' where provider='Tesco' and title='10% off two big shops a month';
update perks set description='10% off selected Tesco own brands in-store, including F&F, Tesco Pet, Fred & Flo, Go Cook and Fox & Ivy.', usage_notes='Usage: In-store only, scan the Clubcard in the Tesco app.' where provider='Tesco' and title='10% off selected Tesco brands';

-- IKEA: hot drink conditions
update perks set description='Free tea or filter coffee in the in-store restaurant, Monday to Friday.', usage_notes='Usage: Mon-Fri only; excludes some smaller-format stores.' where provider='IKEA' and title='Free hot drink';

-- Costco: title already reads 'Optical, tyres and travel services' in the live table — no change needed.

-- ASOS: caveats
update perks set usage_notes='Usage: £15 minimum spend and checkout cut-off apply; excludes Channel Islands and some postcodes.' where provider='ASOS' and title='Unlimited next-day delivery';
update perks set description='Standard delivery, free only above a minimum spend threshold; otherwise charged.' where provider='ASOS' and tier='Free' and title='Standard delivery';

-- Blue Light Card: Deliveroo detail
update perks set description='12 months of free Deliveroo Plus Silver: free delivery on restaurant orders over £15 and grocery orders over £25.', usage_notes='Usage: 1 activation for 12 months, claimed via a unique code.' where provider='Blue Light Card' and title='Free Deliveroo Plus Silver';

-- Deliveroo: thresholds (price stays £7.99 per Ollie's decision)
update perks set description='Free delivery on restaurant orders over £10 and shop orders over £15.' where perk_id='deliveroo-plus-gold-free-delivery-over-10';
update perks set description='Free delivery on restaurant orders over £15 and shop orders over £25. Silver is now available through partners only, not sold directly.', usage_notes='Usage: Ongoing. Partner-only since 2026.' where perk_id='deliveroo-plus-silver-free-delivery-over-15';

-- Amazon: tier rename (also update user_memberships if anyone holds it)
-- update perks set tier='Students and 18-24' where provider='Amazon' and tier='Prime Student';  -- OPTIONAL, breaks perk_id convention; review first

commit;
